<script type="text/javascript" src="/scripts/bootstrap/index.js"></script>
<script>
<?php if ($_GET["passchange"] == "true"): ?>
            popJelloon('affirmative', 'Your password has been successfully changed! Log in with your new password.',5);
<?php endif; ?>
</script>
<!--<ul class="UISegmentControl">
    <li>
        <a href="#" class="segment mobile active">mobile.</a>
    </li>
    <li>
        <a href="#" class="segment desktop">desktop.</a>
    </li>
</ul>-->
<div class="products">
    <div class="section mobile">
        <a href="http://itunes.apple.com/us/app/nightboard/id963223746" class="icon theboard">
            <span class="label">Nightboard</span>
            <span class="illustration"></span>
        </a>
    </div>
    <div class="section desktop hidden">
        <a href="/products/shelf" class="icon shelf">
            <span class="label">Shelf</span>
            <span class="illustration"></span>
        </a>
    </div>
</div>