<!DOCTYPE html>
<html lang="en-US" id="scapehouse" class="403">
  	<head>
    	<title>Scapehouse</title>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="Content-language" content="en" />
		<meta name="description" content="Scapehouse is a social tool that helps you find and share information with the people you want." />
		<link rel="icon" type="image/png" href="DSCAPE/public/graphics/en/UI/favicon.png" />
		<style>
			body {
				background-color: #0073b9;
				color: #333;
				font: 14px 'lucida grande', tahoma, verdana, helvetica, arial, sans-serif;
				margin: 0;
			}
			
			#logo {
				display: block;
				margin: 10px auto;
			}
			
			h2 {
				color: #fff;
				font-size: 32px;
				text-align: center;
				text-shadow: 0 1px 1px #000;
			}
			
			p {
				background-color: #feffdf;
			    border: 1px solid #f5e082;
				margin: 10px auto;
				padding: 10px;
				text-align: center;
				text-shadow: 0 1px 1px #fff;
				-webkit-background-clip: padding-box;
				-webkit-border-radius: 5px;
				-webkit-box-shadow: 0 0 3px #000;
				width: 370px;
			}
		</style>
	</head>
	<body>
		<h1><img id="logo" src="/graphics/en/logos/scapehouse_454px.png" alt="Scapehouse" width="454" height="109" /></h1>
		<h2>BRB.</h2>
		<p>Scapehouse is undergoing some regular maintenance.</p>
	</body>
</html>