<!-- <html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
    <h1>An error occurred</h1>
    <h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

    <h3>Exception information:</h3>
    <p>
        <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo var_export($this->request->getParams(), true) ?>
    </pre>
<?php endif ?>

</body>

</html> -->
<?php if ($this->message == "Page not found"): ?>
<script>
$(document).ready(function() {
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 1000);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 1100);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 2000);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 2200);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 2300);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 2400);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 2600);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 2700);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 2800);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 2850);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 3000);
	
});
</script>

<div class="tip">
	<div class="wrapper">
		<div class="thumbnl">
			<div class="bulb"></div>
		</div>
		<h2 class="name"><a href="http://www.facebook.com/scapehouse">Scapehouse</a></h2>
		<h3 class="username"><a href="http://twitter.com/scapehouse">@Scapehouse</a></h3>
		<div class="tipTxt">
			<p>Psst! Here's a tip for you: the page doesn't exist! Yes, we're sure. We looked everywhere!</p>
		</div>
		<div class="topicStrip">
			<span class="topicWrapper">The page you're looking for</span>
		</div>
	</div>
</div>

<?php endif; ?>

<?php if ($this->message == "Application error"): ?>

<!DOCTYPE html>
<html lang="en-US" id="scapehouse" class="500">
  	<head>
    	<title>An error occurred</title>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="Content-language" content="en" />
		<meta name="description" content="Scapehouse is a social tool that helps you find and share information with the people you want." />
		<link rel="icon" type="image/png" href="/graphics/en/UI/favicon.png" />
		<style>
			body {
				background-color: #0073b9;
				color: #333;
				font: 14px 'lucida grande', tahoma, verdana, helvetica, arial, sans-serif;
				margin: 0;
			}

			a {color:#053497;text-decoration:none;}

			a:hover {text-decoration:underline;}

			#logo {
				display: block;
				margin: 10px auto;
			}

			h2 {
				color: #fff;
				font-size: 32px;
				text-align: center;
				text-shadow: 0 1px 1px #000;
			}

			div {
				background-color: #feffdf;
			    border: 1px solid #f5e082;
				margin: 10px auto;
				padding: 10px;
				text-shadow: 0 1px 1px #fff;
				-webkit-background-clip: padding-box;
				-webkit-border-radius: 5px;
				-webkit-box-shadow: 0 0 3px #000;
				width: 410px;
			}

			p {
				margin: 0 0 5px;
			}

			ul {
				color: #00ad00;
				list-style-type: square;
			}
		</style>
	</head>
	<body>
		<h1><img id="logo" src="/graphics/en/logos/scapehouse_withTransp_454px.png" alt="Scapehouse" width="454" height="109" /></h1>
		<h2>Something somewhere went wrong.</h2>
		<div>
			<p>We're working on fixing it!</p>
				<ul>
					<li><a href="/">Home</a></li>
				</ul>
		</div>
	</body>
</html>

<?php endif; ?>


