<script>
$(document).ready(function() {
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 1000);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 1100);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 2000);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 2200);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 2300);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 2400);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 2600);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 2700);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 2800);
	
	setTimeout(
		"$('.bulb').removeClass('off');"
	, 2850);
	
	setTimeout(
		"$('.bulb').addClass('off');"
	, 3000);
	
});
</script>

<div class="UIContainer">
    <div class="UIInnerContainer">
		<div class="tipHeader">
			<div class="thumbnl">
				<div class="bulb"></div>
			</div>
        	<h3 class="name"><a href="http://www.facebook.com/scapehouse">Scapehouse</a></h3>
			<p class="username"><a href="http://twitter.com/scapehouse">@Scapehouse</a></p>
		</div>
        <div class="tipTxt"><p>Psst! Here's a tip for you: the page doesn't exist! Yes, we're sure. We looked everywhere!</p></div>
		<div class="topicStrip">The page you're looking for</div>
    </div>
</div>