<div id="contentArea">
	<div id="appIcon"></div>
	<h2>Fingereader.</h2>
	<h4 class="headline">YOUR TYPING-FREE DICTIONARY.</h4>
	<div class="mainImage" title="Fingereader"></div>
	<a href="https://itunes.apple.com/us/app/fingereader-by-scapehouse./id859030042" class="storeButton ios" target="_blank">Now available on the<span>App Store</span></a>
	<div class="viralButtons">
		<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-size="large" data-text="Fingereader allows you to the definition of a word by snapping a photo of it." data-related="Scapehouse">Tweet</a>
		<div class="fb-like" data-href="http://scapehouse.com/products/fingereader" data-send="true" data-width="450" data-show-faces="true" data-font="lucida grande" data-action="recommend"></div>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</div>
</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=278585982224213";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>