<div id="contentArea">
	<div id="appIcon"></div>
	<h2>MetroMate.</h2>
	<h4 class="headline">YOUR FRIENDLY NEW GUIDE TO THE DUBAI METRO</h4>
	<div class="mainImage" title="Shelf"></div>
	<div class="feature right timings">
		<h3>train timings.</h3>
		<p>See how long's left till the next train arrives at your station. No need to run when there's still 10 minutes till the next train. MetroMate can show you accurate train timings for any station on both the Red &amp; Green lines.</p>
	</div>
	<div class="feature left stations">
		<h3>smart station detection.</h3>
		<p>You don’t even need to select a station, because MetroMate selects the one nearest to you. All you need to do is select the direction you’re headed to, &amp; you’re set. In fact, you'll no longer even need to carry a map around.</p>
	</div>
	<div class="feature right lastTrain">
		<h3>last train alerts.</h3>
		<p>You’ll be alerted when the last train is leaving your station.</p>
	</div>
	<div class="feature center">
		<h3>are we there yet?</h3>
		<p>Once you’re on the train, you can select the station you’re headed to, &amp; MetroMate will show you how long you need to get there.</p>
	</div>
	<div class="feature left nol">
		<h3>forget about remembering your Nol card balance.</h3>
		<p>Check your Nol card balance. If your balance is running low, MetroMate will send you a notification to remind you to top up your balance, so you don’t get caught up the next time you’re rushing in to catch that train.</p>
	</div>
	<div class="feature right design">
		<h3>a beautiful design.</h3>
		<p>Inspired by the designs of the Dubai Metro stations, MetroMate sports a beautiful interface in both English &amp; Arabic.</p>
	</div>
	<div class="feature left offline">
		<h3>offline access.</h3>
		<p>MetroMate works just fine when offline. You don't need an Internet connection to check train timings.</p>
	</div>
	<a href="https://itunes.apple.com/us/app/metromate-by-scapehouse./id697943749" class="storeButton ios" target="_blank">Now available on the<span>App Store</span></a>
	<div class="viralButtons">
		<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-size="large" data-text="Check out @MetroMate, your friendly guide to the #Dubai Metro! (via @Scapehouse)" data-related="Scapehouse">Tweet</a>
		<div class="fb-like" data-href="http://scapehouse.com/products/metromate" data-send="true" data-width="450" data-show-faces="true" data-font="lucida grande" data-action="recommend"></div>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</div>
</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=278585982224213";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>