<script type="text/javascript" src="/scripts/bootstrap/product_scapes.js"></script>
<div id="contentArea">
	<div id="appIcon"></div>
	<h2>Scapes.</h2>
	<h4 class="headline">THE MESSENGER FOR THE REST OF US</h4>
	<div class="mainImage" title="Scapes"></div>
	<div class="feature center chatCloud">
		<h3>chat cloud.</h3>
		<p>Contact lists are so last century. Introducing the Chat Cloud, a whole new way of seeing your contacts & buddies. Say goodbye to the old fashioned contact list. </p>
		<div class="images">
			<img src="../../../graphics/images/chat_cloud_main.png" width="981" />
			<img src="../../../graphics/images/chat_cloud_1.png" class="hidden" width="981" />
			<img src="../../../graphics/images/chat_cloud_2.png" class="hidden" width="981" />
			<img src="../../../graphics/images/chat_cloud_3.png" class="hidden" width="981" />
			<img src="../../../graphics/images/chat_cloud_4.png" class="hidden" width="981" />
		</div>
		<div class="dotIndicators">
			<a href="#" class="active"></a>
			<a href="#"></a>
			<a href="#"></a>
			<a href="#"></a>
			<a href="#"></a>
		</div>
	</div>
	<div class="feature right miniFeed">
		<h3>mini feed.</h3>
		<p>Mini Feed shows you the latest updates from your friends. Keep up with everything you missed since the last time you came online. You can also see people's status updates inside their chat windows, so the next time someone's battery dies &amp; you're wondering why they're not answering you, you'll find out as soon as you open their chat window.</p>
	</div>
	<div class="feature left adhoc">
		<h3>ad hoc conversations.</h3>
		<p>See which of your contacts are online right now, &amp; who they're chatting with (you can turn this feature off).</p>
	</div>
	<div class="feature center addressBook">
		<h3>address book.</h3>
		<p>Scapes uses your device's address book to automatically find your buddies. Buddies are synced across all your devices.</p>
	</div>
	<div class="feature right usernames">
		<h3>optional usernames.</h3>
		<p>By default, Scapes uses your phone number to allow your contacts to find you. What if you want somebody to add you, but you don't want to give them your phone number? Well, that's why we also allow you to have a unique username.</p>
	</div>
	<div class="feature left devices">
		<h3>multiple devices.</h3>
		<p>You can use the same phone number on as many devices as you want. You're not limited to just one device. Yes, it works with iPod touch as well.</p>
	</div>
	<div class="feature center offline">
		<h3>offline support.</h3>
		<p>Send messages to others even if they're offline. They'll receive a push notification. Send messages even when YOU are offline! </p>
	</div>
	<div class="feature left passcode">
		<h3>built-in passcode lock.</h3>
		<p>Enable passcode locking to keep your messages safe by requiring a passcode every time Scapes is launched.</p>
	</div>
	<div class="feature center other">
		<h3>other good stuff.</h3>
		<p>Fill out your profile, set a display picture, choose custom chat wallpapers, &amp; more.</p>
	</div>
	<a href="https://itunes.apple.com/us/app/scapes-messenger/id737271884" class="storeButton ios" target="_blank">Available now on the<span>App Store</span></a>
	<div class="viralButtons">
		<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-size="large" data-text="Scapes, the messenger for the rest of us." data-related="Scapehouse">Tweet</a>
		<div class="fb-like" data-href="http://scapehouse.com/products/scapes" data-send="true" data-width="450" data-show-faces="true" data-font="lucida grande" data-action="recommend"></div>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</div>
</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=278585982224213";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>