<div id="contentArea">
	<div id="appIcon"></div>
	<h2>Shelf.</h2>
	<h4 class="headline">MANAGING ALL THOSE XCODE PROJECTS HAS NEVER BEEN THIS EASY &amp; ORGANIZED</h4>
	<div class="mainImage" title="Shelf"></div>
	<div class="feature left documents">
		<h3>everything in one place.</h3>
		<p>Add all your existing projects to Shelf. It then conveniently moves them all into one special folder. You'll no longer have to browse through folders &amp; folders to find that project you're looking for. Just add &amp; forget, single-click to launch.</p>
	</div>
	<div class="feature right directories">
		<h3>groups that make sense.</h3>
		<p>Normally when you create a new Xcode project, Xcode just dumps all the new files in one folder. Shelf allows you to create new Xcode projects. The difference is that when you do it through Shelf, it automatically creates a proper directory structure &amp; organizes all your classes, images, NIBs, &amp; other resources in their own folders, with their respective groups created inside Xcode as well.</p>
	</div>
	<div class="feature center">
		<h3>this name doesn't sound right...</h3>
		<p>Shelf allows you to easily rename entire projects. However, you can also choose to just rename the reference inside Shelf without changing any file names.</p>
	</div>
	<div class="feature left thumbnails">
		<h3>it's smart. and beautiful.</h3>
		<p>When you add an existing project to Shelf, it intelligently detects whether what you added is an iPhone project, an iPad project, a binary iOS project, or an OS X project. It then displays the proper device thumbnail for it, either in black or white.</p>
	</div>
	<div class="feature right retina">
		<h3>retina-ready.</h3>
		<p>Shelf is optimized &amp; ready for Retina display Macs. It looks just gorgeous on the high-resolution screen.</p>
	</div>
	<div class="feature center">
		<h3>lots more coming.</h3>
		<p>Shelf started out as an overnight hack. It took one week to get to a usable stage. What you're looking at is the earliest version of it. We've got lots more coming to make Shelf the number one solution when it comes to managing your Xcode projects, so stay tuned! You can keep up with any Shelf news on <a href="http://www.facebook.com/Scapehouse" target="_blank">Facebook</a> &amp; <a href="http://twitter.com/Scapehouse" target="_blank">Twitter</a>.</p>
	</div>
	<a href="https://itunes.apple.com/us/app/shelf-by-scapehouse/id638769575" class="storeButton osx" target="_blank">Now available on the<span>App Store</span></a>
	<div class="minSysRequirements">Requires OS X 10.7 Lion or later.</div>
	<em class="disclaimer">Early adopters: make regular backups of your projects, you know, just in case...</em>
	<div class="viralButtons">
		<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-size="large" data-text="Check out #ScapehouseShelf for easier &amp; more organized management of your Xcode projects. (via @Scapehouse)" data-related="Scapehouse">Tweet</a>
		<div class="fb-like" data-href="http://scapehouse.com/shelf" data-send="true" data-width="450" data-show-faces="true" data-font="lucida grande" data-action="recommend"></div>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</div>
</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=278585982224213";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>