<!DOCTYPE html>
<html lang="en-US" id="scapehouse" class="<?= $this->pageClass; ?>">
    <head <?= $this->facebookThingy; ?>>
        <title id="pageTitle"><?= $this->pageTitle; ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-language" content="en" />
        <meta name="description" content="Tipbox Adminstration" />
        <link rel="icon" type="image/png" href="/graphics/en/UI/favicon.png" />

        <script src="/scripts/lib/jquery.js" type="text/javascript"></script>
        <script src="/scripts/lib/jedit.js" type="text/javascript"></script>

        <script src="/scripts/core.js" type="text/javascript"></script>
        <link href="/stylesheets/css/web/admin.css" media="screen" rel="stylesheet" type="text/css" />

        <script>
    
            $(document).ready(function() {
     
                $('.edit').dblclick(function(elm){
                    window.original = $(this).text();
                });
                
                $('.edit').editable(function(value, settings, original) {
                
                    
                    if($(this).attr("propertyName") == "tip" && $.trim(value) == ""){
                        
                        var responce =confirm("Are you sure you want to delete this tip? This action cannot be rolled back.");
                        
                        if (responce == true)
                        {
                            $(this).parents("tr").remove();
                        }
                        else
                        {
                            return window.original;
                            
                        } 
                        
                    } else if($(this).attr("propertyName") == "topic"){
                        
                        var responce =confirm("Are you sure you want shift this tip to topic '"+value+"'? The operation will only be sucessful if this topic exists. Operation cannot be rolled back if it causes topic deletion.");
                    
                        if (responce == true)
                        {
                            // Carry on
                        }
                        
                        else
                        {
                            return window.original;
                            
                        } 
                    } else if($(this).attr("propertyName") == "tip" && $.trim(value).length > 200){
                        
                        var responce = confirm("This tip contains " + $.trim(value).length + " charaters. Are you sure you want to save this? Max save limit is 220 characters");
                        
                        if (responce == true)
                        {
                            // Carry on
                        }
                        
                        else
                        {
                            return window.original;
                            
                        } 
                        
                    } else if($(this).attr("itemType") == "topic"){
                        
                        var responce = confirm("Are you sure you want to Edit/Merge this topic?");
                        
                        if (responce == true)
                        {
                            // Carry on
                        }
                        
                        else
                        {
                            return window.original;
                            
                        } 
                        
                    }
                   
                    $.ajax({
                        type:"POST",
                        url: "/tipbox/tbadmincon/saveedit",
                        data: "userid=" + encodeURIComponent($(this).attr("userid")) + "&propertyName="+encodeURIComponent($(this).attr("propertyName"))+"&itemType="+encodeURIComponent($(this).attr("itemType"))+"&itemid="+encodeURIComponent($(this).attr("itemid"))+"&value="+encodeURIComponent(value),
                        error: function(e){
                            //alert(e);
                        },
                        success: function(responce) {
                        }
                    });
            
                    return value;
                               
                }, { 
                    type      : 'textarea',
                    cancel    : 'Cancel',
                    submit    : 'OK',
                    indicator : 'Saving...',
                    tooltip   : 'Click to edit...',
                    onblur    : 'ignore',
                    cssclass  : 'editArea',
                    event     : 'dblclick'
                });
            })
 
        </script>

    </head>
    <body>
        <div id="mainWrapper">
            <div id="adminHeader" />
            <div id="tbLogo">
                <img src="/graphics/en/admin/tbIcon.png" height="120px"/>
                <span><?= $this->pageTitle; ?></span>
            </div>

            <div class="controls <?= ($this->pageName == "login") ? "hidden" : NULL; ?>">
                <div class="navButtons">
                    <a class="UIButton" href="/tipbox/tbadmincon/console">Home</a> |
                    <?php if ($this->pageName == "editUser"): ?>
                        <a class="UIButton" href="#">Notify</a> |
                        <a class="UIButton" href="#">Disconnect FB</a> |
                        <a class="UIButton" href="#">Suspend</a> |
                        <a class="UIButton" href="#">Delete</a> 
                    <?php else: ?>
                        <a class="UIButton" href="/tipbox/tbadmincon/userreports">User Reports</a> |
                        <a class="UIButton" href="/tipbox/tbadmincon/tipreports">Tip Reports</a> |
                        <a class="UIButton" href="/tipbox/tbadmincon/alltips">All Tips</a> |
                        <a class="UIButton" href="/tipbox/tbadmincon/alltopics">All Topics</a> |
                        <a class="UIButton" href="/tipbox/tbadmincon/allusers">All Users</a><br />
                    <?php endif; ?>
                    <div style="clear:both;"></div>
                    <div class="logout">
                        <a href="/tipbox/tbadmincon/logout">Logout</a>
                    </div>
                </div>

                <form method="GET" action="/tipbox/tbadmincon/search">
                    <div class="search">
                        <input class="searchBox" type="text" name="query" placeholder="Search" />
                        <input class="UIButton" type="submit" value="Search"/>

                        <div class="searchOptions">
                            <span> <label>Tip: <input type="radio" name="searchType" value="tip"/></label> </span>
                            <span> <label>Topic: <input type="radio" name="searchType" value="topic"/></label> </span>
                            <span> <label>User: <input type="radio" name="searchType" value="user" checked/></label> </span>
                        </div>

                    </div>
                </form>
            </div>
        </div>
        <?= $this->layout()->content; ?>
    </div>
</body>
</html>