<script type="text/javascript" src="/scripts/bootstrap/contact.js"></script>

<div class="divider upper"></div>
<div class="divider lower"></div>
<h3 class="thanks main en">Thanks! :)</h3>
<h3 class="thanks ar" style="top:540px;margin-left:-10px !important;">شكراً</h3>
<h3 class="thanks fr" style="top:540px;margin-left:-300px !important;">Merci!</h3>
<h3 class="thanks ir" style="top:680px;margin-left:40px !important;">ممنونم</h3>
<h3 class="thanks pk" style="top:650px;margin-left:-100px !important;">شکریہً</h3>
<h3 class="thanks hi" style="top:760px;margin-left:100px !important;">धन्यवाद!</h3>
<h3 class="thanks de" style="top:480px;margin-left:-450px !important;">Danke!</h3>
<h3 class="thanks es" style="top:490px;margin-left:-150px !important;">Gracias!</h3>
<h3 class="thanks it" style="top:410px;margin-left:-220px !important;">Grazie!</h3>
<h3 class="thanks cn" style="top:460px;margin-left:100px !important;">谢谢！</h3>
<h3 class="thanks jp" style="top:600px;margin-left:130px !important;">ありがとう！</h3>
<h3 class="thanks ko" style="top:405px;margin-left:-400px !important;">감사합니다!</h3>
<h3 class="thanks gr" style="top:660px;margin-left:-300px !important;">Ευχαριστώ!</h3>
<h3 class="thanks tr" style="top:600px;margin-left:-420px !important;">Teşekkürler!</h3>
<h3 class="thanks ru" style="top:760px;margin-left:-400px !important;">Спасибо!</h3>
<h3 class="thanks phi" style="top:720px;margin-left:-150px !important;">Salamat!</h3>
<h3 class="thanks sw" style="top:410px;margin-left:20px !important;">Shukrani!</h3>
<div class="theLove"></div>
<div class="runwayMarker"></div>
<div class="envelope"></div>
<div id="contentArea">
	<div class="UIHeader">
		<h2>send us a message.</h2>
		<p>We welcome your comments and questions.</p>
	</div>
	<div id="contactForm">
		<form method="post">
			<div class="recipientInfo">
				<p>Scapehouse</p>
				<p>Dubai, United Arab Emirates</p>
			</div>
			<label for="email"><span class="UILabel">email.</span>
				<div class="inputContainer">
					<input type="text" id="email" name="email" class="UITextInput" />
				</div>
			</label>
			<label for="fullname"><span class="UILabel">name.</span>
				<div class="inputContainer">
					<input type="text" id="fullname" name="fullname" class="UITextInput" />
				</div>
			</label>
			<label for="msg"><span class="UILabel">message.</span>
				<div class="inputContainer">
					<textarea id="msg" name="msg"></textarea>
				</div>
			</label>
			<div class="UIPanel">
				<label class="UIButton large green submit" onclick="return false">
					<input type="submit" value="Send Message" />
				</label>
			</div>
		</form>
	</div>
</div>