<div id="contentArea">
	<h2>Scapehouse Privacy Policy.</h2>
	<p>We all have private things in our lives that we would rather not share with other people. At Scapehouse, we respect that fact. Your privacy is important to us, and we will not violate the trust you place in us.</p>
	<p>Information you provide through this service will not be abused, distributed, or sold, nor will any of your information be provided to third parties without your permission.</p>
	<p>You have full control over your information, and your information can be removed from our data banks at anytime upon your request.</p>
	<h3>Information Collection and Use</h3>
	<ul>
		<li>
			<h4>Signup</h4>
			<p>Upon joining a Scapehouse service, we collect some information from you (varies by service).</p>
		</li>
		<li>
			<h4>Third Party Services</h4>
			<p>The Scapehouse website uses Google Analytics. Google Analytics helps us understand our visitors and how they use our website. It collects information such as your IP address. This information is also sent to Google and their use of it is governed by their <a href="http://www.google.com/intl/en/privacy.html">Privacy Policy</a>.</p>
		</li>
	</ul>
	<h3>Your Personal Information</h3>
	<p>You have complete control over your personal information. If you wish, you can change these details or even remove them.</p>
	<h3>How We Use Your Information</h3>
	<p>We may use your information to contact you regarding changes to our services. You may opt out of non-essential communication.</p>
	<p>We may use your information to help us manage and improve our services and to provide you with support.</p>
	<em class="footnote">This Privacy Policy is subject to change. If we do make changes, we will notify you.</em>
</div>