<div id="contentArea">
	<h2>Terms &amp; Conditions.</h2>
	<p>These Terms &amp; Conditions ("<strong>Terms</strong>") govern your access to and use of Scapehouse's products &amp; services (the "<strong>Services</strong>"), and any information, text, graphics, or other materials uploaded, downloaded or appearing on the Services (the "<strong>Content</strong>"). THIS SERVICE IS PROVIDED AS IS WITH NO WARRANTY WHATSOEVER. USE IT AT YOUR OWN RISK. WE DO NOT GUARANTEE THAT SCAPEHOUSE WILL BE SAFE OR SECURE. YOU ARE RESPONSIBLE FOR YOUR USE OF SCAPEHOUSE PRODUCTS, FOR ANY CONTENT YOU POST ON SCAPEHOUSE PRODUCTS, AND FOR ANY CONSEQUENCES THEREOF. By using or accessing Scapehouse's products &amp; services, you agree to these Terms.</p>
	<h3>Copyright</h3>
	<p>We respect the intellectual property rights of others and expect users of the Services to do the same. Occurrences of third-party trademarks might be found in the Content on the Services. We claim no ownership of any of those trademarks. Those trademarks are the copyright and legal property of their corresponding owners.</p>
	<h3>Links</h3>
	<p>The Services may contain links to third-party websites or resources. You acknowledge and agree that we are not responsible or liable for the availability or accuracy of such websites or resources; or the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by Scapehouse of such websites or resources or the content, products, or services available from such websites or resources.</p>
	<h3>Protecting Other People's Rights</h3>
	<p>You will not post content or take any action on the Services that infringes or violates someone else's rights or otherwise violates the law. We reserve the right to remove any content or information you post on the Services if we believe that it violates these Terms.</p>
	<h3>Your Rights</h3>
	<p>You hold the copyright to your own content and are therefore responsible for any content you post to the Services. We will not be held liable for any direct, indirect, special, incidental, consequential or punitive damages, including but not limited to, the loss of profits, data, use, good-will, or other intangible losses, resulting from your access to or use of or inability to access or use the Services.</p>
	<p><strong>Medical Information:</strong> You should consult your doctor or physician before acting on medical information you find on the Services. We do not guarantee that such information may be valid.</p>
	<h3>Privacy</h3>
	<p>Any information you provide us with is subject to Scapehouse's <a href="privacy">Privacy Policy</a>.</p>
	<h3>Safety</h3>
	<p>Safety is a very important issue at Scapehouse. We take all the necessary measures to ensure your safety and the safety of others while using the Services, but we can cannot guarantee it. By using the Services, you agree that:
	<ol>
		<li>You will not use Scapehouse to do anything unlawful, misleading, discriminatory, or malicious.</li>
		<li>You will not upload any malicious code (viruses, etc.).</li>
		<li>You will not solicit login information or access an account belonging to someone else.</li>
		<li>You will not intimidate, bully, or harass any user.</li>
		<li>You will not post any content that is hateful, pornographic, threatening, or that contains nudity or violence.</li>
		<li>You will not send or otherwise post unauthorised commercial communications (such as spam).</li>
		<li>You will not collect users' content or information, or otherwise access the Services, using automated means (such as robots, spiders, or scrapers) without our permission.</li>
		<li>You will not do anything that could overload, disable, or disrupt the Services.</li>
	</ol>
	</p>
	<h3>Accounts</h3>
	<p>Inactive accounts will not be deleted. If you are reported to be behaving inappropriately or in any way that violates these Terms, your account will be suspended.</p>
	<!--<h3>Usernames</h3>
	<p>A username is your unique name on Scapehouse. It is also part of the link to your profile (http://scapehouse.com/&lt;username&gt;).</p>
	<p>Scapehouse reserves the right to remove and/or reclaim any username at any time for any reason.</p>-->
	<h3>Children</h3>
	<p>The Services are not directed at people under the age of 13. If we become aware that a child under 13 has provided us with personal information, we take steps to remove such information and terminate the child's account.</p>
	<em class="footnote">These Terms are subject to change. If we do change them, we will notify you.</em>
</div>