<script src="/scripts/lib/jquery.js" type="text/javascript"></script>
<script>
    
function postCall(){
    
    $('#status').html("").append("Processing....");

    var tip = $('#tip').val();
    var username = $('#username').val();
    var topic = $('#topic').val();
    var cat = $('#cat').val();
    var fbPost = ($("#fbPost:checked").length === 1)?1:0;
    
    
    $.ajax({
        type:"POST",
        url: "/test/fbtesttipper",
        data: "username="+encodeURIComponent(username)+"&content="+encodeURIComponent(tip)+"&topicContent="+encodeURIComponent(topic)+"&catid="+encodeURIComponent(cat)+"&fbPost="+encodeURIComponent(fbPost),
        error: function(e){
            alert(e);
        },
        success: function(responce) {
	
          
          $('#status').html("").append("Tip Posted!" + ".... RESPONCE -> "+responce);
			
        }
    });
    
}
</script>
<h1> Facebook Test Tipper </h1>
Tip:<textarea rows="5" cols="20" id="tip"></textarea>
Topic:<input type="text" id="topic"/>
Category:<select id="cat">
    <?php
    $tbcatTable = new Tipbox_Model_DbTable_Tbcat();
    $cats = $tbcatTable->getCats("thing");
    $cats = array_merge($cats, $tbcatTable->getCats("place"));
    $cats = array_merge($cats, $tbcatTable->getCats("idea"));

    foreach ($cats as $cat):
        ?>    

        <option value="<?= $cat["id"]; ?>"><?= $cat["parentcat"]; ?> : <?= $cat["subcat"]; ?></option>

<?php endforeach; ?>

</select>
Post to FB:<input type="checkbox" value="fbPost" id="fbPost"/>
<input type="button" value="submit" onclick="postCall()" />
<hr/>
<h3>Status:</h3><h4 id="status">Idle...</h4>
<hr/>