<span class="tableHeader">Total tips: <?= count($this->tips);?></span>

<table id="hor-minimalist-b" class="tipTable">
    <tr>
        <th>Tip&nbsp;id</th>
        <th>User</th>
        <th>Tip</th>
        <th>Topic</th>
        <th>Cat</th>
        <th>Time</th>
    </tr>
    <?php foreach($this->tips as $tip): ?>
    <tr>
        <td><?=$tip["id"];?></td>
        <td><a href="/tipbox/tbadmincon/edituser?username=<?=$tip["username"];?>" target="_blank"><?=$tip["username"] . ":" . $tip["userid"];?></a></td>
        <td class="edit" userid="<?=$tip["userid"];?>" propertyName="tip" itemid="<?= $tip["id"]; ?>" itemType="tip"><?= htmlentities($tip["content"]);?></td>
        <td class="edit" userid="<?=$tip["userid"];?>" propertyName="topic" itemid="<?= $tip["id"]; ?>" itemType="tip"><?= htmlentities($tip["topicContent"]);?></td>
        <td><?=$tip["parentcat"] . ":" . $tip["subcat"];?></td>
        <td><?= Model_Lib_Func::relativeTimeShort(strtotime($tip["time"]));?></td>
    </tr>
    <?php endforeach; ?>
</table>