<div id="stats">
    <table id="hor-minimalist-b" class="statTable">
        <th>Stat Name</th>
        <th>#</th>
        <tr>
            <td>Total Users</td>
            <td><?=$this->userCount;?></td>
        </tr>
        <tr>
            <td>Total Tips</td>
            <td><?=$this->tipCount;?></td>
        </tr>
        <tr>
            <td>Total Topics</td>
            <td><?=$this->topicCount;?></td>
        </tr>
        <tr>
            <td>Unchecked User Reports</td>
            <td><?=$this->userReportCount;?></td>
        </tr>
        <tr>
            <td>Unchecked Tip Reports</td>
            <td><?=$this->tipReportCount;?></td>
        </tr>
    </table>
</div>
