<form action="/tipbox/tbadmincon/createuser" method="POST"> 
    <table id="hor-minimalist-b" class="userTable">
        <th><div style="min-width: 350px; width: 350px;">Detail Name</div></th>
        <th><div style="min-width: 350px; width: 350px;">Value</div></th>

        <tr>
            <td>Fullname</td>
            <td propertyName="fullname" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="fullname" /></td>
        </tr>   

        <tr>
            <td>Email</td>
            <td propertyName="email" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="email" /></td>
        </tr>

        <tr>
            <td>Username</td>
            <td propertyName="username" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="username" /></td>
        </tr>
        <tr>
            <td>Bio</td>
            <td  propertyName="bio" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="bio" /></td>
        </tr>
        <tr>
            <td>Location</td>
            <td  propertyName="location" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="location" /></td>
        </tr>
        <tr>
            <td>Website</td>
            <td  propertyName="website" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="url" /></td>
        </tr>
        <tr>
            <td>Facebook ID</td>
            <td  propertyName="FB" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="fbid" /></td>
        </tr>
        <tr>
            <td>Password</td>
            <td  propertyName="FB" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="password" /></td>
        </tr>
        <tr>
            <td>Password Confirm</td>
            <td  propertyName="FB" itemid="<?= $this->user["id"]; ?>" itemType="user"><input name="passwordConfirm" /></td>
        </tr>
    </table>
    <button type="submit" style="float:right;">Create User</button>
</form>