<div id="formHolder" align="left">
    <input class="submitButton" type="button" onclick="$('#loginForm').submit();" value="Login"/>
    <div class="form">
        <form action="/tipbox/tbadmincon/login" id="loginForm" method="post">

            <input class="texual" type="text" name="username" placeholder="Username"/> <br />
            <input class="texual" type="password" name="password" placeholder="Password"/>
        </form>
        <br/>
        <?php if($_GET["authErr"] == "true"): ?>
        <div class="errorFieldHolder" align="center">
            <span class="errorField">Incorrect username or password.</span>
        </div>
        <?php endif; ?>
    </div>
</div>